In [4]:
from google.colab import drive
drive.mount("/content/gdrive")

import pandas as pd

destination_filename = "/content/gdrive/My Drive/" + "player_data.csv"

players = pd.read_csv(destination_filename,
                      names = ["Team", 
                               "Wins", 
                               "Losses",
                               "Coins Collected",
                               "Quests",
                               "Red Color",
                               "Armor Lost",
                               "Fans",
                               "Mentions",
                               "Days on Team",
                               "Timeouts",
                               "Blue Color",
                               "Green Color"])

players.head()
players.shape
players.describe().transpose()

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

                 count        mean         std  ...      50%        75%      max
Team             170.0   13.662059    2.167048  ...   13.050    13.8175    19.83
Wins             170.0    2.738294    2.117400  ...    1.875     2.9875     9.98
Losses           170.0    2.467294    0.362142  ...    2.370     2.7900     3.23
Coins Collected  170.0   20.234118    3.702807  ...   19.700    21.8000    30.00
Quests           170.0  100.700000   15.407617  ...   98.500   108.0000   181.00
Red Color        170.0    2.440412    0.623300  ...    2.700     2.9175     3.90
Armor Lost       170.0    2.213529    1.036851  ...    2.200     2.9200     8.08
Fans             170.0    0.494706    0.286588  ...    0.320     0.8200     0.98
Mentions         170.0    1.720000    0.573355  ...    1.825     1.9800     3.88
Days on Team     170.0    6.367000    2.968234  ...    7.540     8.8800    13.00
Timeouts         170.0    1.016218    0.205640  ...    0.990     1.1200     1.98
Blue Color       170.0    2.781706    0.851168  ...    2.870     3.1900     9.00
Green Color      170.0  903.594118  298.629245  ...  880.000  1013.0000  1980.00

[13 rows x 8 columns]